# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 397360ce2f6e75c3f7f76a88a4d4615d7fbc1ee984dd7cf7b6db07035aa7fd9262433ee235e807a8d160526c6b4f2a39d480128a9efd12cbcbf9d3faead29333

test:
  secret_key_base: f415f886b7aebaf9036df25d4266e189dde13022ee6b863e47861e8e4c1039ef3e654c31595d84ffd514e1079807dd765b12fe911c304b5d9a94f2dc30ab9c4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
